In [1]:
print("Hello world!")

Hello world!


Bu nvidia-smi buyrug`i GPU ni statisticasini chiqarib beradi

In [2]:
!nvidia-smi


Fri Oct 10 09:21:45 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.65.06              Driver Version: 580.65.06      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti     Off |   00000000:01:00.0  On |                  N/A |
| N/A   44C    P8              9W /   80W |     736MiB /   6144MiB |     24%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu129


Introduction to Tensor

Creating tensors

In [4]:
# scalars, vectors, matrices, tensors
# 0D, 1D, 2D, 3D, nD tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# learn Torch tensors are created using torch.tensor() function

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int 
scalar.item() 

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim # this number of square brackets indicates the number of dimensions

1

In [10]:
vector.shape    # shape of the tensor describes how many elements in each dimension

torch.Size([2])

In [11]:
# MTRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim # this number of square brackets indicates the number of dimensions
   # shape of the tensor describes how many elements in each dimension

2

In [13]:
MATRIX.shape # rows, columns

torch.Size([2, 2])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[0] # first row


tensor([7, 8])

In [16]:
MATRIX[1] # second row

tensor([ 9, 10])

In [17]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR.ndim


3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0] # first matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Random Tensors are important because the way many neural networks  learn is that tey start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [21]:
random_tensor = torch.rand(3, 4) # 3D tensor of random numbers between 0 and 1
random_tensor

tensor([[0.4343, 0.9695, 0.3289, 0.2321],
        [0.8126, 0.6510, 0.0362, 0.2700],
        [0.8009, 0.9563, 0.1418, 0.4242]])

In [22]:
random_tensor.ndim

2

In [23]:
random_image_size = torch.rand(224, 224, 3) # height, width, color channels (RGB)
random_image_size.shape , random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [24]:
torch.rand(size=(3, 4)) # another way of creating a random tensor


tensor([[0.9664, 0.0131, 0.2613, 0.2828],
        [0.8424, 0.9553, 0.8488, 0.0924],
        [0.5527, 0.2103, 0.2841, 0.8291]])

In [25]:
# Create a tensor of all zeros 
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
torch.arange(0, 10) # deprecated


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
float_32_tensor = torch.tensor([2.0, 3.0, 10.0], dtype=None)
float_32_tensor,  float_32_tensor.dtype


(tensor([ 2.,  3., 10.]), torch.float32)

In [31]:
float_tensor = torch.tensor([3.0, 6.0, 9.0], 
                            dtype=torch.float32,
                            device = None,
                            requires_grad = False) # specify the datatype of a tensor upon creation
float_tensor, float_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [32]:
float_tensor_16 = float_tensor.type(torch.float16)
float_tensor_16, float_tensor_16.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [33]:
float_tensor * float_tensor_16


tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3, 4, 5], dtype = torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [35]:
int_32_tensor * float_tensor_16

tensor([ 9., 24., 45.], dtype=torch.float16)

In [36]:
int_32_tensor_new = torch.tensor([3,4,5], dtype = torch.long) # Bu variant int32 ni urniga log ni ham yozsa buladi 
int_32_tensor_new

tensor([3, 4, 5])

### Getting information from tensors

In [37]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2746, 0.3252, 0.4513, 0.6686],
        [0.0333, 0.7912, 0.0650, 0.0912],
        [0.0468, 0.0173, 0.5610, 0.6623]])

# Find out detials about some tensor


In [38]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2746, 0.3252, 0.4513, 0.6686],
        [0.0333, 0.7912, 0.0650, 0.0912],
        [0.0468, 0.0173, 0.5610, 0.6623]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulating Tensors (tensor  operations)
Tensor operations include 
* Addition
* Subtraction
* Multiplications
* Division
* Matrix multiplication



In [39]:
tensor = torch.tensor([1, 2, 4])
tensor + 12 
 

tensor([13, 14, 16])

In [40]:
tensor * 10 # kupaytirish amali


tensor([10, 20, 40])

In [41]:
tensor - 10 # ayirish amali


tensor([-9, -8, -6])

In [42]:
tensor / 10 # Bulish amali 


tensor([0.1000, 0.2000, 0.4000])

# Try out PyTorch build-in functions

In [43]:
torch.mul(tensor, 10) # kupaytirish

tensor([10, 20, 40])

In [44]:
torch.add(tensor, 10) 

tensor([11, 12, 14])

In [45]:
print(tensor , '*' , tensor)
print(f"Equals: {tensor * tensor }")


tensor([1, 2, 4]) * tensor([1, 2, 4])
Equals: tensor([ 1,  4, 16])


In [46]:
torch.matmul(tensor, tensor)

tensor(21)

In [47]:
%%time 
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value


CPU times: user 1.55 ms, sys: 0 ns, total: 1.55 ms
Wall time: 1.09 ms


tensor(21)

In [48]:
a = [1,2,4,5,6,7]
for i in a:

    print(i)

1
2
4
5
6
7


In [49]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 384 μs, sys: 60 μs, total: 444 μs
Wall time: 310 μs


tensor(21)

In [50]:
tensor @ tensor 

tensor(21)

The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work 

In [51]:
torch.matmul(torch.rand(2,3), torch.rand(3, 2)).shape

torch.Size([2, 2])

# One of the most common errors in deep learning : Shape errors

In [52]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,19],
                         [11,23]])
#torch.mm(tensor_A, tesnor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code )
  

In [53]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

# To fix out tensor shape issues, we can manipulate the shape of one of our tensors useing transpose\
# A transpose switches the axes or dimensions of a given tensor

In [54]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 19, 23]])

In [55]:
tensor_B


tensor([[ 7,  8],
        [ 9, 19],
        [11, 23]])

In [56]:
tensor_B.T.shape


torch.Size([2, 3])

In [57]:
tensor_B.shape # transpose 3,2 ni 2, 3 ga uzgartiradi

torch.Size([3, 2])

In [58]:
tensor_A.shape

torch.Size([3, 2])

In [59]:
print(f"Original shapes of tensors: tensor_A = {tensor_A.shape}, tesnor_B = {tensor_B.shape}")
print(f"New shapes: tesor_A = {tensor_A} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Muplitlying: {tensor_A.shape} @ {tensor_B.T.shape}")
print("Output:\n ")
output = torch.matmul(tensor_B.T, tensor_A)
print(output)
print(output.shape)


Original shapes of tensors: tensor_A = torch.Size([3, 2]), tesnor_B = torch.Size([3, 2])
New shapes: tesor_A = tensor([[1, 2],
        [3, 4],
        [5, 6]]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Muplitlying: torch.Size([3, 2]) @ torch.Size([2, 3])
Output:
 
tensor([[ 89, 116],
        [180, 230]])
torch.Size([2, 2])


In [60]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [61]:
torch.min(x), x.min() # find the min
x.dtype

torch.int64

In [62]:
torch.max(x), x.max() # find the max

(tensor(90), tensor(90))

In [63]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() 
# Find the mean - note: the torch .mean() function requires a tensor of float32 to work

(tensor(45.), tensor(45.))

In [64]:
# Find the sum 
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [65]:
# Findinf the positions of min and max 
x   

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
# Find the position in tensor that has the  minimum value with argmin() -> returns index position of target tensor 
x.argmin()

tensor(0)

In [67]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [68]:
x[9]

tensor(90)

# Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View -Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multipe  vtack tesnors on top of each other (vstack) or side by side  hstack
* Squeeze - removes all one dimensions from a tensor
* Unsqueeze - add a one dinstions to a target tensor

* Permute - return a view of the input with dimenstions permuted (swapped) in certain way  

In [69]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
# Add an extra dimension
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
x_reshaped = x.reshape(1, 9) # Add an extra dimension 
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
z = x.view(1, 9)  # Change the view 
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [74]:
# stack tensor on top of each other \
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
# troch.squeeze()- remove all single dimensions from a target tensor
 

In [76]:


x = torch.zeros(2, 1, 2, 1, 2)
x.size
y = torch.squeeze(x)
y.size()
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [77]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [78]:
x_reshaped.shape

torch.Size([1, 9])

In [79]:
x_squeezed = x_reshaped.squeeze()

In [80]:
x_reshaped.squeeze().shape

torch.Size([9])

# torch.unsqueeze() - adds a single dimension to a target tesnor at a specific dim (dimenson)


In [81]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed 

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [82]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order 
x_original = torch.rand(size = (224, 224,3)) 
x_permuted = x_original.permute(2, 0, 1)    # shift axis 0->1, 1>2, 2>0
x_permuted, x_permuted.shape, x_original.shape

(tensor([[[3.2899e-01, 9.4775e-01, 4.0468e-01,  ..., 1.6546e-01,
           1.7340e-01, 8.1469e-01],
          [4.9219e-01, 2.4427e-01, 7.8016e-02,  ..., 2.8733e-01,
           8.1879e-01, 9.5867e-01],
          [7.9610e-01, 7.8064e-01, 9.1931e-01,  ..., 7.6977e-01,
           4.3605e-01, 8.1612e-01],
          ...,
          [1.7337e-01, 5.5090e-01, 4.1423e-01,  ..., 1.4201e-01,
           9.7185e-04, 5.3041e-01],
          [6.3797e-01, 2.0331e-01, 1.9911e-01,  ..., 7.2315e-01,
           1.7996e-01, 5.3905e-01],
          [5.6692e-01, 2.7416e-01, 4.1924e-01,  ..., 9.9414e-01,
           6.7729e-01, 1.2631e-01]],
 
         [[5.8108e-01, 1.8053e-01, 5.8499e-01,  ..., 3.8907e-01,
           5.8767e-01, 7.3375e-01],
          [1.8144e-01, 5.6621e-01, 7.6133e-01,  ..., 5.5237e-01,
           3.3023e-01, 6.3567e-01],
          [5.6410e-01, 7.6364e-01, 6.0699e-01,  ..., 2.6104e-01,
           6.9781e-01, 5.0791e-01],
          ...,
          [8.5097e-01, 4.0093e-01, 6.4082e-01,  ..., 1.044

In [83]:
x_original

tensor([[[3.2899e-01, 5.8108e-01, 2.8503e-01],
         [9.4775e-01, 1.8053e-01, 9.6421e-01],
         [4.0468e-01, 5.8499e-01, 9.7073e-01],
         ...,
         [1.6546e-01, 3.8907e-01, 5.6093e-01],
         [1.7340e-01, 5.8767e-01, 9.4672e-01],
         [8.1469e-01, 7.3375e-01, 7.5164e-01]],

        [[4.9219e-01, 1.8144e-01, 6.8894e-01],
         [2.4427e-01, 5.6621e-01, 7.9829e-01],
         [7.8016e-02, 7.6133e-01, 1.3165e-01],
         ...,
         [2.8733e-01, 5.5237e-01, 3.4324e-01],
         [8.1879e-01, 3.3023e-01, 9.7834e-01],
         [9.5867e-01, 6.3567e-01, 7.5316e-01]],

        [[7.9610e-01, 5.6410e-01, 3.1790e-01],
         [7.8064e-01, 7.6364e-01, 8.5819e-01],
         [9.1931e-01, 6.0699e-01, 8.6084e-01],
         ...,
         [7.6977e-01, 2.6104e-01, 9.7195e-01],
         [4.3605e-01, 6.9781e-01, 8.4691e-01],
         [8.1612e-01, 5.0791e-01, 2.8117e-01]],

        ...,

        [[1.7337e-01, 8.5097e-01, 4.7386e-01],
         [5.5090e-01, 4.0093e-01, 2.6266e-01]

## Indexing (selecting data from tensor)
Indexing with PyTorch is simmilar to indexing with NumPy

In [84]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
# let's index on  our new tensor
x[0][0]
# x[0], x[0][1]

tensor([1, 2, 3])

In [86]:
# Let's index on the most inner bracket(last dimension)\
x[0][2][2]

tensor(9)

In [87]:
x[:, 0], x[:, :, 1]


(tensor([[1, 2, 3]]), tensor([[2, 5, 8]]))

In [88]:
x[:, 1, 1]

tensor([5])

In [89]:
x[0, 0, :]

tensor([1, 2, 3])

In [90]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to retur 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


NumPy is a popular scientific Python numerical computing library 
* And because of this, PyTorch has functionality to interact with it.


* Data in NumPy, want in PyTorch tensor-> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [91]:
# Numpy array to tensor
import torch
import numpy as np


array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
array.dtype

dtype('float64')

In [93]:
tensor.dtype

torch.float64

In [94]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [95]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor, tensor.dtype


(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [96]:
array = array + 1 
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [97]:
# Tensor to NumPy
tesnor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

In [98]:
# Change the tensor, what happens to "numpy_tensor"?
tensor = tensor + 1
tensor, numpy_tensor 

(tensor([2., 3., 4., 5., 6., 7., 8.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

In [99]:
torch.rand(3, 3)

tensor([[0.5072, 0.6821, 0.0733],
        [0.1940, 0.3015, 0.6615],
        [0.5035, 0.9242, 0.3204]])

# Learn PyTorch reproducebility 

In [100]:
import torch


rand_tensor_A = torch.rand(3, 4)
rand_tensor_B = torch.rand(3, 4)

print(f"A rand tensor: {rand_tensor_A}, \n B rand tensor: {rand_tensor_B}")
print(rand_tensor_A == rand_tensor_B)


A rand tensor: tensor([[0.3402, 0.8951, 0.2575, 0.8008],
        [0.5195, 0.9029, 0.6219, 0.3573],
        [0.0676, 0.9377, 0.6732, 0.2072]]), 
 B rand tensor: tensor([[0.9292, 0.7267, 0.4256, 0.4171],
        [0.5835, 0.8399, 0.9550, 0.0378],
        [0.2283, 0.9842, 0.8138, 0.0697]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [101]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)


print(random_tensor_c)
print(random_tensor_d)

print(random_tensor_c == random_tensor_d)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and PyTorch objects on the GPUs (and makeing faster computation)

In [102]:
# GPU = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everythibg hunky dory(good) 

In [103]:
### 1. getting a GPU

# 1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
# 2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there are lots of options...
# tim dettmeres gpu
# 3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

## For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: it https://pytorch.org/get-started/locally/

In [109]:
!nvidia-smi

Fri Oct 10 09:22:17 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.65.06              Driver Version: 580.65.06      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti     Off |   00000000:01:00.0  On |                  N/A |
| N/A   45C    P8              7W /   80W |     720MiB /   6144MiB |      5%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [111]:
import torch 

torch.cuda.is_available()

True

In [108]:
torch.__version__

'2.8.0+cu129'

In [114]:
device  = "cuda" if torch.cuda.is_available() else "cpu"
device 

'cuda'

In [116]:
# Count number of devices 
torch.cuda.device_count()

1

In [118]:
# Putting tensors (and models) on the GPU
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [122]:
# Move tensor to GPU ( if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [123]:
# Moving tensors back to the CPU
# If tensor is on GPU, can't transform it to NumPy 
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

# To fix the GPU tensorwith NumPy issue we can first set it to the GPU

In [128]:
tensor_run_cpu = tensor_on_gpu.cpu().numpy()
tensor_run_cpu

array([1, 2, 3])

In [129]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')