In [2]:
print("Hello world!")

Hello world!


Bu nvidia-smi buyrug`i GPU ni statisticasini chiqarib beradi

In [3]:
!nvidia-smi


Tue Oct  7 14:30:38 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.65.06              Driver Version: 580.65.06      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti     Off |   00000000:01:00.0  On |                  N/A |
| N/A   46C    P8              7W /   80W |     707MiB /   6144MiB |     28%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [12]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu128


Introduction to Tensor

Creating tensors

In [15]:
# scalars, vectors, matrices, tensors
# 0D, 1D, 2D, 3D, nD tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# learn Torch tensors are created using torch.tensor() function

In [16]:
scalar.ndim

0

In [18]:
# Get tensor back as Python int 
scalar.item() 

7

In [19]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # this number of square brackets indicates the number of dimensions

1

In [22]:
vector.shape    # shape of the tensor describes how many elements in each dimension

torch.Size([2])

In [23]:
# MTRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [29]:
MATRIX.ndim # this number of square brackets indicates the number of dimensions
   # shape of the tensor describes how many elements in each dimension

2

In [32]:
MATRIX.shape # rows, columns

torch.Size([2, 2])

In [34]:
MATRIX.ndim

2

In [36]:
MATRIX[0] # first row


tensor([7, 8])

In [38]:
MATRIX[1] # second row

tensor([ 9, 10])

In [41]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [43]:
TENSOR.ndim


3

In [45]:
TENSOR.shape

torch.Size([1, 3, 3])

In [48]:
TENSOR[0] # first matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Random Tensors are important because the way many neural networks  learn is that tey start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [54]:
random_tensor = torch.rand(3, 4) # 3D tensor of random numbers between 0 and 1
random_tensor

tensor([[0.9188, 0.9530, 0.1738, 0.1899],
        [0.5204, 0.0556, 0.7219, 0.2832],
        [0.1210, 0.1537, 0.0440, 0.7371]])

In [55]:
random_tensor.ndim

2

In [56]:
random_image_size = torch.rand(224, 224, 3) # height, width, color channels (RGB)
random_image_size.shape , random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [58]:
torch.rand(size=(3, 3)) # another way of creating a random tensor


tensor([[0.9161, 0.8093, 0.1883],
        [0.9379, 0.8551, 0.4200],
        [0.2140, 0.0468, 0.8951]])

In [64]:
# Create a tensor of all zeros 
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [65]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [68]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [69]:
ones.dtype

torch.float32

In [72]:
torch.arange(0, 10) # deprecated


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
float_32_tensor = torch.tensor([2.0, 3.0, 10.0], dtype=None)
float_32_tensor,  float_32_tensor.dtype


(tensor([ 2.,  3., 10.]), torch.float32)

In [82]:
float_tensor = torch.tensor([3.0, 6.0, 9.0], 
                            dtype=torch.float16,
                            device = None,
                            requires_grad = False) # specify the datatype of a tensor upon creation
float_tensor, float_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)