In [7]:
print("Hello world!")

Hello world!


Bu nvidia-smi buyrug`i GPU ni statisticasini chiqarib beradi

In [8]:
!nvidia-smi


Wed Oct  8 17:42:49 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.65.06              Driver Version: 580.65.06      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti     Off |   00000000:01:00.0  On |                  N/A |
| N/A   46C    P8              6W /   80W |     653MiB /   6144MiB |     20%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu128


Introduction to Tensor

Creating tensors

In [15]:
# scalars, vectors, matrices, tensors
# 0D, 1D, 2D, 3D, nD tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# learn Torch tensors are created using torch.tensor() function

In [16]:
scalar.ndim

0

In [18]:
# Get tensor back as Python int 
scalar.item() 

7

In [19]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # this number of square brackets indicates the number of dimensions

1

In [22]:
vector.shape    # shape of the tensor describes how many elements in each dimension

torch.Size([2])

In [23]:
# MTRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [29]:
MATRIX.ndim # this number of square brackets indicates the number of dimensions
   # shape of the tensor describes how many elements in each dimension

2

In [32]:
MATRIX.shape # rows, columns

torch.Size([2, 2])

In [34]:
MATRIX.ndim

2

In [36]:
MATRIX[0] # first row


tensor([7, 8])

In [38]:
MATRIX[1] # second row

tensor([ 9, 10])

In [41]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [43]:
TENSOR.ndim


3

In [45]:
TENSOR.shape

torch.Size([1, 3, 3])

In [48]:
TENSOR[0] # first matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Random Tensors are important because the way many neural networks  learn is that tey start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [54]:
random_tensor = torch.rand(3, 4) # 3D tensor of random numbers between 0 and 1
random_tensor

tensor([[0.9188, 0.9530, 0.1738, 0.1899],
        [0.5204, 0.0556, 0.7219, 0.2832],
        [0.1210, 0.1537, 0.0440, 0.7371]])

In [55]:
random_tensor.ndim

2

In [56]:
random_image_size = torch.rand(224, 224, 3) # height, width, color channels (RGB)
random_image_size.shape , random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [12]:
torch.rand(size=(3, 4)) # another way of creating a random tensor


NameError: name 'torch' is not defined

In [64]:
# Create a tensor of all zeros 
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [65]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

In [13]:
torch.arange(0, 10) # deprecated


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
float_32_tensor = torch.tensor([2.0, 3.0, 10.0], dtype=None)
float_32_tensor,  float_32_tensor.dtype


(tensor([ 2.,  3., 10.]), torch.float32)

In [20]:
float_tensor = torch.tensor([3.0, 6.0, 9.0], 
                            dtype=torch.float32,
                            device = None,
                            requires_grad = False) # specify the datatype of a tensor upon creation
float_tensor, float_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [22]:
float_tensor_16 = float_tensor.type(torch.float16)
float_tensor_16, float_tensor_16.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [23]:
float_tensor * float_tensor_16


tensor([ 9., 36., 81.])

In [25]:
int_32_tensor = torch.tensor([3, 4, 5], dtype = torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [27]:
int_32_tensor * float_tensor_16

tensor([ 9., 24., 45.], dtype=torch.float16)

In [ ]:
int_32_tensor_new = torch.tensor([3,4,5], dtype = torch.long) # Bu variant int32 ni urniga log ni ham yozsa buladi 
int_32_tensor_new

tensor([3, 4, 5])

### Getting information from tensors

In [30]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9132, 0.9572, 0.6001, 0.9595],
        [0.9975, 0.3634, 0.8276, 0.4299],
        [0.5197, 0.7970, 0.8236, 0.2269]])

# Find out detials about some tensor


In [32]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9132, 0.9572, 0.6001, 0.9595],
        [0.9975, 0.3634, 0.8276, 0.4299],
        [0.5197, 0.7970, 0.8236, 0.2269]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulating Tensors (tensor  operations)
Tensor operations include 
* Addition
* Subtraction
* Multiplications
* Division
* Matrix multiplication



In [6]:
tensor = torch.tensor([1, 2, 4])
tensor + 12 
 

tensor([13, 14, 16])

In [ ]:
tensor * 10 # kupaytirish amali


tensor([10, 20, 40])

In [ ]:
tensor - 10 # ayirish amali


tensor([-9, -8, -6])

In [52]:
tensor / 10 # Bulish amali 


tensor([0.1000, 0.2000, 0.4000])

# Try out PyTorch build-in functions

In [7]:
torch.mul(tensor, 10) # kupaytirish

tensor([10, 20, 40])

In [56]:
torch.add(tensor, 10) 

tensor([11, 12, 14])

In [63]:
print(tensor , '*' , tensor)
print(f"Equals: {tensor * tensor }")


tensor([1, 2, 4]) * tensor([1, 2, 4])
Equals: tensor([ 1,  4, 16])


In [8]:
torch.matmul(tensor, tensor)

tensor(21)

In [66]:
%%time 
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value


CPU times: user 3.35 ms, sys: 1.08 ms, total: 4.42 ms
Wall time: 9.59 ms


tensor(21)

In [73]:
a = [1,2,4,5,6,7]
for i in a:

    print(i)

1
2
4
5
6
7


In [15]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 44 μs, sys: 7 μs, total: 51 μs
Wall time: 54.6 μs


tensor(21)

In [16]:
tensor @ tensor 

tensor(21)

The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work 

In [19]:
torch.matmul(torch.rand(2,3), torch.rand(3, 2)).shape

torch.Size([2, 2])

# One of the most common errors in deep learning : Shape errors

In [23]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,19],
                         [11,23]])
#torch.mm(tensor_A, tesnor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code )
  

In [24]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

# To fix out tensor shape issues, we can manipulate the shape of one of our tensors useing transpose\
# A transpose switches the axes or dimensions of a given tensor

In [27]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 19, 23]])

In [28]:
tensor_B


tensor([[ 7,  8],
        [ 9, 19],
        [11, 23]])

In [30]:
tensor_B.T.shape


torch.Size([2, 3])

In [ ]:
tensor_B.shape # transpose 3,2 ni 2, 3 ga uzgartiradi

torch.Size([3, 2])

In [34]:
tensor_A.shape

torch.Size([3, 2])

In [43]:
print(f"Original shapes of tensors: tensor_A = {tensor_A.shape}, tesnor_B = {tensor_B.shape}")
print(f"New shapes: tesor_A = {tensor_A} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Muplitlying: {tensor_A.shape} @ {tensor_B.T.shape}")
print("Output:\n ")
output = torch.matmul(tensor_B.T, tensor_A)
print(output)
print(output.shape)


Original shapes of tensors: tensor_A = torch.Size([3, 2]), tesnor_B = torch.Size([3, 2])
New shapes: tesor_A = tensor([[1, 2],
        [3, 4],
        [5, 6]]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Muplitlying: torch.Size([3, 2]) @ torch.Size([2, 3])
Output:
 
tensor([[ 89, 116],
        [180, 230]])
torch.Size([2, 2])
