In [1]:
import torch
data = [1, 2, 3, 4, 5]
v_data = torch.tensor(data)
print(v_data)

tensor([1, 2, 3, 4, 5])


In [2]:
x = torch.randn(3, 4, 5)

d = torch.randn(3, 4, 5, dtype = torch.float64)
d, x

(tensor([[[ 0.8473, -0.7839,  1.0505,  0.2394,  0.1651],
          [-1.2120, -0.2884,  0.9448, -0.9474, -0.5664],
          [-0.5228,  0.7189, -1.4021,  0.0332,  1.5680],
          [-0.1183,  0.3822,  0.2637,  0.6080,  0.8967]],
 
         [[-0.2503, -0.6725,  0.9487,  1.3290, -2.5550],
          [-0.8085,  0.2799,  0.4924, -0.8492, -0.4800],
          [-1.3407, -0.3282, -0.7248, -0.6441,  0.9694],
          [ 0.5347, -0.7558,  1.3679, -0.3848,  0.7338]],
 
         [[-0.3089, -2.2886,  0.2882, -0.6511,  0.0942],
          [-0.2213, -0.0042,  0.6410, -0.2145, -0.5608],
          [-0.7876, -0.4298,  1.5528,  0.3125,  1.0998],
          [ 1.4919, -0.4479,  0.1621, -0.7559,  1.7567]]], dtype=torch.float64),
 tensor([[[-2.0641e+00, -8.1564e-01, -1.5994e+00, -3.4718e-01, -9.2123e-02],
          [-8.0257e-01, -1.4371e+00,  1.2366e+00,  4.5547e-01,  2.8273e-01],
          [ 6.2389e-01,  1.6404e+00, -1.7669e-01,  2.4701e-01, -1.9432e-03],
          [ 1.0960e+00, -2.6605e-01,  4.5783e-01,  3.17

In [3]:
import torch 

a = torch.zeros(4, 5, 3, dtype = torch.int32)
a

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)

In [4]:
x = torch.ones(4, 5, dtype = torch.int32)
x
c = torch.ones([3, 4, 5], dtype = torch.float32)
c

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [ ]:
torch.full((3, 4, 5), 3.14, dtype = torch.float32, device = 'cpu', requires_grad = False, pin_memory = False, memory_format = torch.preserve_format)

tensor([[[3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
         [3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
         [3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
         [3.1400, 3.1400, 3.1400, 3.1400, 3.1400]],

        [[3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
         [3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
         [3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
         [3.1400, 3.1400, 3.1400, 3.1400, 3.1400]],

        [[3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
         [3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
         [3.1400, 3.1400, 3.1400, 3.1400, 3.1400],
         [3.1400, 3.1400, 3.1400, 3.1400, 3.1400]]])

In [6]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

y = torch.full_like(x, 9)
print(y)

tensor([[9, 9, 9],
        [9, 9, 9]])


In [8]:
newTensor= torch.full((4, 3), 3.14,dtype= torch.float32)
print(newTensor)


tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])


In [ ]:
x = torch.full_like(newTensor,3.24, dtype=None ) # Bu function tensorning o'lchamini saqlab qoladi
print(x)

tensor([[3.2400, 3.2400, 3.2400],
        [3.2400, 3.2400, 3.2400],
        [3.2400, 3.2400, 3.2400],
        [3.2400, 3.2400, 3.2400]])


In [12]:
torch.device('cuda:0') # Bu funksiyani vazifasi qurilmani tanlash va 
torch.dtype(torch.float32) # Bu funksiyani vazifasi tensorning ma'lumot turini tanlash

TypeError: cannot create 'torch.dtype' instances