In [32]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
torch.__version__

'2.8.0+cu129'

In [34]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([5, 4, 3])
x + y
x * y
x / y
x - y
print(x + y)
print(x * y)
print(x / y)
print(x - y)

tensor([6, 6, 6])
tensor([5, 8, 9])
tensor([0.2000, 0.5000, 1.0000])
tensor([-4, -2,  0])


In [35]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
a.shape

torch.Size([2, 3])

In [37]:
b = a.view(3, 2) # reshapedan farqi bu 
b

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [38]:
b.reshape(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
x = torch.tensor([2.0], requires_grad=True)
y = x ** 2
y
z = 2 * y + 5
z.backward()
x.grad

tensor([8.])

In [40]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(1, 10)
        self.fc2 = nn.Linear(10, 1)

    def forward(self, x):
        x = F.relu(self.fc1(x)) # F ni vazifasi aktivatsiya funksiyasini chaqirish 
        x = self.fc2(x)
        return x 
    
net = Net()
net


Net(
  (fc1): Linear(in_features=1, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=1, bias=True)
)

In [41]:
net = Net()

# Model training 

In [43]:
import torch.optim as optim


criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

# load random data
inputs = torch.randn([1, 1, 32, 32])
output = net(inputs)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x32 and 1x10)

In [4]:
import numpy as np
tc = np.array([25.5, 28.1, 30.6])
tk = [round(c * 9/5 + 32, 2) for c in tc]
print(tk)
# [77.9, 82.58, 87.08]


[np.float64(77.9), np.float64(82.58), np.float64(87.08)]
